### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by ryuryu10** [Bowlingtoolkit/Xenon-Bot-JavaScript-Edition#8]
(node:1352) DeprecationWarning: Guild#createChannel: Create channels with an options object instead of separate parameters
(node:1352) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at C:\Users\ryury\OneDrive za\XenonCrack\XenonCrack\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\ryury\OneDrive - za\XenonCrack\XenonCrack\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This error occurs when you give the robot the role of administrator and the role of the highest level.
And I don't think the channel's rights are applied, and the role is created redundant.

**Comment by ryuryu10** [comment]
It doesn't load channel permissions .

**Comment by REVENGE977** [comment]
it seems the bot doesnt have enough permissions .
